### ISSUE TITLE
ROS2 

### ISSUE THREAD

**Issue by Miftahur92** [panagelak/rgbd_unity_camera#2]
Hi, thank you for sharing this excellent work. Do you have any version for ROS2?

**Comment by panagelak** [comment]
Hello @Miftahur92 not yet maybe soon ; )
meanwhile this is built upon robotics hub https://github.com/Unity-Technologies/Unity-Robotics-Hub
which can be built for ros2 also with the ros2 tcp endpoint https://github.com/Unity-Technologies/ROS-TCP-Endpoint/tree/main-ros2

Since i created this package it has come to my attention this package https://github.com/Field-Robotics-Japan/UnitySensors 
,built upon robotics hub, which implements most sensors with some issues i noticed for rgbd sensor
pointcloud  accurate fast - no color
depth image is rgb8 instead of 32fc1 (you will need to decompress them in ros2 side)
camera info topics are so so 
you can try the latest branch of this repo feature/commonPublisher or master 
also you can copy this repo to your unity assets folder to have the latest
Cheers

**Comment by Miftahur92** [comment]
> Hello @Miftahur92 not yet maybe soon ; ) meanwhile this is built upon robotics hub https://github.com/Unity-Technologies/Unity-Robotics-Hub which can be built for ros2 also with the ros2 tcp endpoint https://github.com/Unity-Technologies/ROS-TCP-Endpoint/tree/main-ros2
> 
> Since i created this package it has come to my attention this package https://github.com/Field-Robotics-Japan/UnitySensors ,built upon robotics hub, which implements most sensors with some issues i noticed for rgbd sensor pointcloud accurate fast - no color depth image is rgb8 instead of 32fc1 (you will need to decompress them in ros2 side) camera info topics are so so you can try the latest branch of this repo feature/commonPublisher or master also you can copy this repo to your unity assets folder to have the latest Cheers

Thank you @panagelak
